"""Subclass of MyFrame1, which is generated by wxFormBuilder."""

import wx
import webbrowser

# Implementing MyFrame1
class MayaBrowserMyFrame1( webbrowser.MyFrame1 ):
	def __init__( self, parent ):
		webbrowser.MyFrame1.__init__( self, parent )
	
